### ISSUE TITLE
64位精度问题解决方案

### ISSUE THREAD

**Issue by Fuatnow** [Justin-sky/Nice-TS#2]
64位精度有啥问题啊，没有替换，自己测试64位也没发现啥问题啊

**Comment by Justin-sky** [comment]
pbjs 生成的代码引用的是protobufjs版本是：   var $protobuf = require("protobufjs/minimal");

**Comment by Fuatnow** [comment]
> pbjs 生成的代码引用的是protobufjs版本是： var $protobuf = require("protobufjs/minimal");
我说呢，我是用require("protobufjs")替换的。谢谢大佬答疑。

**Comment by Justin-sky** [comment]
no problem
